### PR TITLE
Request for review: OpenSSL 1.1 support

### PR DESCRIPTION
**Pull request by hillu**
Hi,

here's my first attempt at getting ncrack built with OpenSSL 1.1. All code that has been touched seems opensshlib-related. Please do not blindly merge; this needs review by somebody who is more familiar with the codebase than I am. I also could use some advice on how to test the code. Please note that the code will currently not build with OpenSSL 1.0 and below -- quite a few getter/setter functions or macros have to be added to openssl-compat.h.

### CODE REVIEW

**Comment by ithilgore** [comment]
Thanks for the great work! I will be reviewing your changes in the following days.
As for the testing, I would try to mainly see if the SSH module is working as it should (trying to see if it can successfully find valid credentials) - conducting tests against at least the latest OpenSSH server versions (7.6.p1) and a few older ones.
 
I will be doing these tests myself too, but feel free to mention here the ones you have successfully tested so far.

**Comment by ithilgore** [comment]
Successfully compiled on latest Kali (openssl 1.1.0f) and ran against OpenSSH_7.4p1

**Comment by rhertzog** [comment]
So is this good to merge?

**Comment by ithilgore** [comment]
Yes, it was just merged. Did some more testing - will have to keep an eye for future changes in the OpenSSH code for conflicts though.

**Pull request merged**
